const mongoose=require('mongoose');
const db={};
const {DB_URL}=require('../configuration/config');
const {User}=require("./userModel");
const { Account } = require('./accountModel');
db.mongoose=mongoose;
db.url=DB_URL;
db.users=User
db.accounts=Account
module.exports=db;
